# Generated by Django 5.0.6 on 2024-06-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='system_name',
            field=models.CharField(max_length=222),
        ),
    ]
