# Generated by Django 5.0.6 on 2024-06-26 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('devname', models.CharField(blank=True, max_length=255, null=True)),
                ('devid', models.CharField(blank=True, max_length=100, null=True)),
                ('eventtime', models.BigIntegerField()),
                ('tz', models.CharField(blank=True, max_length=10, null=True)),
                ('logid', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('subtype', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('vd', models.CharField(blank=True, max_length=50, null=True)),
                ('srcip', models.GenericIPAddressField(blank=True, null=True)),
                ('srcname', models.CharField(blank=True, max_length=255, null=True)),
                ('srcport', models.IntegerField(blank=True, null=True)),
                ('srcintf', models.CharField(blank=True, max_length=50, null=True)),
                ('srcintfrole', models.CharField(blank=True, max_length=50, null=True)),
                ('dstip', models.GenericIPAddressField(blank=True, null=True)),
                ('dstport', models.IntegerField(blank=True, null=True)),
                ('dstintf', models.CharField(blank=True, max_length=50, null=True)),
                ('dstintfrole', models.CharField(blank=True, max_length=50, null=True)),
                ('srccountry', models.CharField(blank=True, max_length=100, null=True)),
                ('dstcountry', models.CharField(blank=True, max_length=100, null=True)),
                ('sessionid', models.BigIntegerField(blank=True, null=True)),
                ('proto', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('policyid', models.IntegerField(blank=True, null=True)),
                ('policytype', models.CharField(blank=True, max_length=50, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('trandisp', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('sentbyte', models.BigIntegerField(blank=True, null=True)),
                ('rcvdbyte', models.BigIntegerField(blank=True, null=True)),
                ('sentpkt', models.BigIntegerField(blank=True, null=True)),
                ('rcvdpkt', models.BigIntegerField(blank=True, null=True)),
                ('appcat', models.CharField(blank=True, max_length=100, null=True)),
                ('crscore', models.CharField(blank=True, max_length=11, null=True)),
                ('craction', models.CharField(blank=True, max_length=11, null=True)),
                ('crlevel', models.CharField(blank=True, max_length=50, null=True)),
                ('srchwvendor', models.CharField(blank=True, max_length=100, null=True)),
                ('mastersrcmac', models.CharField(blank=True, max_length=50, null=True)),
                ('srcmac', models.CharField(blank=True, max_length=50, null=True)),
                ('srcserver', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=222)),
                ('system_type', models.CharField(choices=[('normal', 'Normal'), ('server', 'Server')], max_length=6)),
                ('system_ip', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'system_configuration',
            },
        ),
        migrations.CreateModel(
            name='SystemIPPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_ip_range', models.GenericIPAddressField()),
                ('to_ip_range', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'system_ip_pool',
            },
        ),
        migrations.AddConstraint(
            model_name='systemconfiguration',
            constraint=models.UniqueConstraint(fields=('system_name', 'system_ip'), name='unique_system_name_system_ip'),
        ),
        migrations.AddField(
            model_name='systemippool',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ip_pools', to='backend.department'),
        ),
    ]
